[build-system]
requires = [
  "setuptools>=61.0",
  "wheel",
]
build-backend = "setuptools.build_meta"

[project]
name = "datateam_moss"
version = "0.0.44"
authors = [
  { name="Robbin Breeuwer", email="r.j.breeuwer@amsterdam.nl" },
  { name="Fried SchÃ¶lvinck", email="f.scholvinck@amsterdam.nl"}
]
description = "Functions needed for datateam MOSS (municipality of Amsterdam)"
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
  "tabulate==0.9.0",
  "pandas==1.4.4",
  "xxhash==3.4.1"
]
